name: Continuous Integration
on:
  push:
    paths-ignore:
      - '**.md'
jobs:
  to-do-app-tests:
    name: run pytests
    runs-on: ubuntu-latest
    steps:
    -  uses: actions/checkout@v2
    -  run: docker build --target test --tag my-test-image .
    -  run: docker run my-test-image