name: Continuous Integration
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  terraform:
    name: Build Azure Infrastructure
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      v_secret_key: ${{ secrets.secret_key }}

    steps:
    -   uses: actions/checkout@v2
    -   run: terraform init
    -   run: terraform apply -auto-approve
    
  to-do-app-production:
    name: Build and Deploy to Azure
    runs-on: ubuntu-latest
    #needs: to-do-app-tests
    #if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    -  uses: actions/checkout@v2
    #-  run: docker build --target production --tag ${{ secrets.DOCKERHUB_USERNAME }}/todoapp .
    #-  run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    #-  run: docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/todoapp
    #-  run: curl -dH -X POST "${{ secrets.JP_AZURE_WEBHOOK}}"